SELECT DISTINCT 
	TO_CHAR(PEAI.EXT_IDENTIFIER_ID) "ExternalIdentifierId"
	, TO_CHAR(PEAI.DATE_TO, 'YYYY/MM/DD') "DateTo"
	, PEAI.EXT_IDENTIFIER_NUMBER "ExternalIdentifierNumber"
	, PEAI.COMMENTS "Comments"
	, PEAI.EXT_IDENTIFIER_TYPE "ExternalIdentifierType"
	, TO_CHAR(PEAI.DATE_FROM, 'YYYY/MM/DD') "DateFrom"
	, TO_CHAR(PEAI.PERSON_ID) "PersonId"
	, PEAI.EXT_IDENTIFIER_SEQ "ExternalIdentifierSequence"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
	, PEAI.CREATED_BY "CreatedBy"
	, TO_CHAR(PEAI.CREATION_DATE, 'YYYY/MM/DD') "CreationDate"
	, PEAI.LAST_UPDATED_BY "LastUpdatedBy"
	, TO_CHAR(PEAI.LAST_UPDATE_DATE, 'YYYY/MM/DD') "LastUpdateDate"
	, PAPF.PERSON_NUMBER "PersonNumber"
	, PAAM.ASSIGNMENT_NUMBER "AssignmentNumber"
FROM PER_EXT_APP_IDENTIFIERS PEAI
	, HRC_INTEGRATION_KEY_MAP HIKM
	, PER_ALL_PEOPLE_F PAPF
	, PER_ALL_ASSIGNMENTS_M PAAM
WHERE 1 = 1
	AND PEAI.EXT_IDENTIFIER_ID = HIKM.SURROGATE_ID
	AND HIKM.OBJECT_NAME = 'ExternalIdentifier'
	AND PEAI.PERSON_ID = PAPF.PERSON_ID
	AND PAAM.PERSON_ID = PAPF.PERSON_ID
	AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
	AND DECODE(:SelectRecords, 'ALL', SYSDATE, PAPF.EFFECTIVE_START_DATE) <= SYSDATE
	AND DECODE(:SelectRecords, 'ALL', SYSDATE, PAPF.EFFECTIVE_END_DATE) >= SYSDATE
	AND DECODE(:SelectRecords, 'ALL', SYSDATE, PAAM.EFFECTIVE_START_DATE) <= SYSDATE
	AND DECODE(:SelectRecords, 'ALL', SYSDATE, PAAM.EFFECTIVE_END_DATE) >= SYSDATE
ORDER BY PAPF.PERSON_NUMBER, PAAM.ASSIGNMENT_NUMBER, TO_CHAR(PEAI.DATE_FROM, 'YYYY/MM/DD'), TO_CHAR(PEAI.DATE_TO, 'YYYY/MM/DD'), PEAI.EXT_IDENTIFIER_NUMBER, PEAI.EXT_IDENTIFIER_TYPE;
